seed: 1337
deterministic: false
gpu: -1
name: null
experiments_dir: /data/je/experiments
debug: false
load_model: null
data:
  dir: /data/je/mimiciv/pre-processed
  data_filename: mimiciv_icd9_preprocessed.feather
  split_filename: mimiciv_icd9_split.feather
  code_column_names:
  - icd9_diag
  - icd9_proc
  max_length: 4000
dataset:
  name: HuggingfaceDataset
  configs:
    chunk_size: 128
dataloader:
  max_batch_size: 1
  batch_size: 16
  num_workers: 2
  drop_last: true
  batch_sampler:
    name: BySequenceLengthSampler
    configs:
      bucket_boundaries:
      - 400
      - 600
      - 800
      - 1000
      - 1200
      - 1400
      - 1600
      - 1800
      - 2000
      - 2200
      - 2600
      - 3000
      - 4000
model:
  name: PLMICD
  configs:
    model_path: /data/je/pretrained_models/RoBERTa-base-PM-M3-Voc-hf
text_encoder: {}
trainer:
  epochs: 20
  validate_on_training_data: true
  print_metrics: false
  use_amp: true
  threshold_tuning: true
optimizer:
  name: AdamW
  configs:
    lr: 5.0e-05
    weight_decay: 0
lr_scheduler:
  name: linear
  configs:
    num_warmup_steps: 2000
label_transform:
  name: OneHotEncoder
  configs: {}
text_transform:
  name: HuggingFaceTokenizer
  configs:
    model_path: /data/je/pretrained_models/RoBERTa-base-PM-M3-Voc-hf
    add_special_token: true
    padding: false
    use_fast: true
    do_lower_case: true
    max_length: null
    truncation: false
metrics:
- name: F1Score
  configs:
    average: micro
    threshold: 0.5
- name: F1Score
  configs:
    average: macro
    threshold: 0.5
- name: Recall
  configs:
    average: micro
    threshold: 0.5
- name: Recall
  configs:
    average: macro
    threshold: 0.5
- name: Precision
  configs:
    average: micro
    threshold: 0.5
- name: Precision
  configs:
    average: macro
    threshold: 0.5
- name: FPR
  configs:
    average: micro
    threshold: 0.5
- name: FPR
  configs:
    average: macro
    threshold: 0.5
- name: ExactMatchRatio
  configs:
    threshold: 0.5
- name: Precision_K
  configs:
    k: 5
- name: Precision_K
  configs:
    k: 8
- name: Precision_K
  configs:
    k: 15
- name: Recall_K
  configs:
    k: 10
- name: Recall_K
  configs:
    k: 15
- name: MeanAveragePrecision
  configs: {}
- name: PrecisionAtRecall
  configs: {}
- name: AUC
  configs:
    average: micro
- name: AUC
  configs:
    average: macro
- name: LossMetric
  configs: {}
lookup:
  code_description:
    code_desc_path: null
    code_column: null
    desc_column: null
callbacks:
- name: WandbCallback
  configs:
    project: automatic-medical-coding
    entity: null
    dir: /data/je
- name: SaveBestModelCallback
  configs:
    split: val
    target: all
    metric: map
- name: EarlyStoppingCallback
  configs:
    split: val
    target: all
    metric: map
    patience: 6
data.max_length: 4000
